# Cuadro Magico

In [1]:
import deap.algorithms as algorithms
import deap.base as base
import deap.creator as creator
import deap.tools as tools

import numpy as np 
import random

In [2]:
N = 4; N2 = N**2; k = N*(N2+1)/2

In [3]:
creator.create('FitnessMin', base.Fitness, weights=(-1.0,))
creator.create('Individual', list, fitness=creator.FitnessMin)

In [4]:
toolbox = base.Toolbox()

# Generador Atributos
toolbox.register('indices', random.sample, range(N2), N2)

# Inicializar Estructuras
toolbox.register('individual', tools.initIterate, creator.Individual, toolbox.indices)
toolbox.register('population', tools.initRepeat, list, toolbox.individual)

In [5]:
def evalMS(individual):
    ms = np.array(individual).reshape((N,N)) + 1
    tot = 0.0
    for i in range(N):
        tot += abs(k - sum(ms[i,:]))
        tot += abs(k - sum(ms[:,i]))
    tot += abs(k - sum(ms.diagonal()))
    tot += abs(k - sum(np.rot90(ms).diagonal()))
    return tot,

In [6]:
toolbox.register("evaluate", evalMS)
toolbox.register("select", tools.selTournament, tournsize=3)
toolbox.register("mate", tools.cxPartialyMatched)
toolbox.register("mutate", tools.mutShuffleIndexes, indpb=0.05)

In [11]:
pop = toolbox.population(n=5000)

hof = tools.HallOfFame(1)
stats = tools.Statistics(lambda ind: ind.fitness.values)
stats.register("avg", np.mean)
stats.register("std", np.std)
stats.register("min", np.min)
stats.register("max", np.max)

algorithms.eaSimple(pop, 
    toolbox, 
    cxpb=0.7, 
    mutpb=0.2, 
    ngen=100, 
    stats=stats, 
    halloffame=hof)

gen	nevals	avg    	std    	min	max
0  	5000  	66.6768	12.9473	22 	102
1  	3785  	60.5976	12.809 	21 	107
2  	3770  	58.136 	13.7246	19 	102
3  	3836  	57.1162	14.2441	15 	105
4  	3771  	55.7212	14.7458	13 	99 
5  	3722  	54.4352	14.9018	13 	102
6  	3794  	53.847 	15.5128	12 	103
7  	3834  	53.9302	15.8166	15 	102
8  	3801  	53.0046	15.9356	15 	102
9  	3739  	53.098 	16.1059	13 	99 
10 	3768  	52.8268	16.0159	15 	102
11 	3761  	52.6398	16.2747	15 	104
12 	3812  	52.707 	16.4077	14 	100
13 	3748  	52.1276	16.2984	11 	98 
14 	3845  	52.8396	16.3507	11 	102
15 	3803  	53.153 	16.4668	15 	101
16 	3876  	53.3114	16.3343	15 	100
17 	3754  	52.5422	16.3023	12 	101
18 	3815  	52.1824	16.3183	8  	103
19 	3870  	52.197 	16.4248	15 	102
20 	3799  	52.2916	16.8695	14 	102
21 	3804  	51.7862	16.8952	14 	104
22 	3762  	51.306 	16.9872	14 	107
23 	3790  	51.2708	17.0251	14 	103
24 	3813  	51.2438	16.6577	14 	102
25 	3846  	51.28  	16.6462	12 	102
26 	3800  	51.1852	16.4988	9  	103
27 	3778  	51.1282	1

([[15, 6, 0, 9, 3, 2, 13, 12, 11, 8, 7, 4, 1, 14, 10, 5],
  [15, 6, 0, 9, 3, 2, 13, 12, 11, 8, 7, 4, 1, 14, 10, 5],
  [15, 6, 0, 9, 3, 2, 13, 12, 11, 8, 7, 4, 1, 14, 10, 5],
  [15, 6, 0, 9, 3, 2, 13, 12, 11, 8, 7, 4, 1, 14, 10, 5],
  [15, 6, 0, 9, 3, 2, 13, 12, 11, 8, 7, 4, 1, 14, 10, 5],
  [15, 6, 0, 9, 3, 2, 13, 12, 11, 8, 7, 4, 1, 14, 10, 5],
  [15, 6, 0, 9, 3, 2, 13, 12, 11, 8, 7, 4, 1, 14, 10, 5],
  [15, 6, 0, 9, 3, 2, 13, 12, 11, 8, 7, 4, 1, 14, 10, 5],
  [15, 6, 0, 9, 3, 2, 13, 12, 11, 8, 7, 4, 1, 14, 10, 5],
  [15, 6, 0, 9, 3, 2, 13, 12, 11, 8, 7, 4, 1, 14, 10, 5],
  [15, 6, 0, 9, 3, 2, 13, 12, 11, 8, 7, 4, 1, 14, 10, 5],
  [11, 6, 3, 9, 0, 5, 8, 12, 15, 13, 7, 4, 1, 14, 10, 2],
  [15, 6, 0, 9, 3, 2, 13, 12, 11, 8, 7, 4, 1, 14, 10, 5],
  [15, 6, 0, 9, 3, 2, 1, 12, 11, 8, 7, 4, 13, 14, 10, 5],
  [15, 6, 0, 9, 3, 2, 13, 12, 11, 8, 7, 4, 1, 14, 10, 5],
  [15, 6, 0, 9, 3, 2, 13, 12, 11, 8, 7, 4, 1, 14, 10, 5],
  [15, 6, 0, 9, 3, 2, 13, 12, 11, 8, 7, 4, 1, 14, 10, 5],
  [15, 6, 0, 9

In [12]:
print(np.array(hof[0]).reshape((N,N)) + 1)

[[16  7  1 10]
 [ 4  3 14 13]
 [12  9  8  5]
 [ 2 15 11  6]]
